import { useNavigate } from "react-router-dom";
import { useCake } from "../context/CakeContext";
import UploadOrderSection from "../components/UploadOrderSection";
import { SHAPES, FLAVORS, LAYER_OPTIONS, FONDANTS, FROSTINGS, findById } from "../data/cakeOptions";
import { formatPKR } from "../utils/pricing";

// Real, premium cake photography swapped in for the placeholder tiles.
// Clicking one loads the closest matching preset into the builder so the
// person can start from something in that spirit and customize further --
// clearly labelled as a starting point, not a claim that the photo itself
// is generated by the tool.
const MOST_LOVED = [
  {
    name: "Pink Butterfly Tier",
    image: "/assets/most-loved/butterfly-cake.jpg",
    priceFrom: 3200,
    preset: { shape: "heart", flavor: "strawberry", layers: 2, fondant: "blush", frosting: "whipped" },
  },
  {
    name: "Heart Confetti Cake",
    image: "/assets/most-loved/heart-dots-cake.jpg",
    priceFrom: 2800,
    preset: { shape: "round", flavor: "vanilla", layers: 2, fondant: "ivory", frosting: "whipped" },
  },
  {
    name: "Butterfly & Candle Bloom",
    image: "/assets/most-loved/pink-butterfly-candle-cake.jpg",
    priceFrom: 3000,
    preset: { shape: "round", flavor: "strawberry", layers: 2, fondant: "blush", frosting: "whipped" },
  },
];

function presetToCake(preset) {
  return {
    shape: findById(SHAPES, preset.shape),
    flavor: findById(FLAVORS, preset.flavor),
    layers: findById(LAYER_OPTIONS, preset.layers),
    fondant: findById(FONDANTS, preset.fondant),
    frosting: findById(FROSTINGS, preset.frosting),
    toppings: [],
    text: { value: "", x: 50, y: 18, rotation: 0, freehandPaths: [] },
    candles: [],
  };
}

export default function Home() {
  const navigate = useNavigate();
  const { dispatch } = useCake();

  function startWithPreset(item) {
    dispatch({ type: "LOAD", payload: presetToCake(item.preset) });
    navigate("/decorate/toppings");
  }
    
  return (
    <div>
      {/* Hero: full viewport, flat black/white overlay chrome on top of the video */}
      <section className="relative w-screen h-screen -mt-px overflow-hidden bg-ink">
        <video
          className="absolute inset-0 w-full h-full object-cover"
          src="/video/batter-mix.mp4"
          autoPlay
          loop
          muted
          playsInline
        />
        <div className="absolute inset-0 bg-gradient-to-b from-ink/35 via-transparent to-ink/50" />

        <div className="absolute inset-0 flex flex-col items-center justify-center px-4">
          <h1 className="font-display tracked-xl text-white text-5xl sm:text-7xl md:text-8xl text-center">
            Cak&eacute;
          </h1>
        </div>

        <div className="absolute inset-x-0 bottom-0 flex flex-col items-center pb-10 sm:pb-14 gap-5">
          <p className="tracked text-white/90 text-xs sm:text-sm">Design it. Bake it. Celebrate.</p>
          <button
            onClick={() => navigate("/decorate/shape")}
            className="px-10 py-3.5 bg-white text-ink tracked text-xs hover:bg-ink hover:text-white border border-white transition-colors duration-200"
          >
            Start Decorating
          </button>
        </div>
      </section>

      {/* Upload-your-own-design shortcut, directly above Most Loved as requested */}
      <UploadOrderSection />

      {/* Most Loved: real cake photography tiles */}
      <section id="most-loved" className="max-w-7xl mx-auto px-4 sm:px-8 py-16 sm:py-24 scroll-mt-24">
        <div className="flex items-end justify-between mb-8 border-b border-line pb-4">
          <h2 className="font-display tracked-xl text-2xl sm:text-3xl">Most Loved</h2>
          <p className="text-ink-soft text-xs tracked hidden sm:block">Tap to start decorating a similar cake</p>
        </div>

        <div className="grid sm:grid-cols-3 gap-px bg-line">
          {MOST_LOVED.map((item) => (
            <button
              key={item.name}
              onClick={() => startWithPreset(item)}
              className="group relative bg-bone text-left overflow-hidden aspect-[3/4]"
            >
              <img
                src={item.image}
                alt={item.name}
                className="absolute inset-0 w-full h-full object-cover scale-100 group-hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-ink/80 via-ink/10 to-transparent" />
              <div className="absolute inset-x-0 bottom-0 p-5 flex flex-col items-center text-center">
                <p className="font-display tracked text-sm sm:text-base text-white">{item.name}</p>
                <p className="text-xs text-white/80 mt-1">From {formatPKR(item.priceFrom)}</p>
              </div>
            </button>
          ))}
        </div>
      </section>

      {/* how it works */}
      <section className="max-w-7xl mx-auto px-4 sm:px-8 pb-20 sm:pb-28">
        <div className="grid sm:grid-cols-3 border-t border-b border-line divide-y sm:divide-y-0 sm:divide-x divide-line">
          {[
            { title: "Build it layer by layer", body: "Shape, flavor, fondant, frosting — watch it come together live." },
            { title: "Decorate it your way", body: "Drag on toppings, write a message, or draw it freehand." },
            { title: "Order it for real", body: "Checkout securely and we'll bake exactly what you designed." },
          ].map((item) => (
            <div key={item.title} className="p-8 text-center">
              <p className="font-display tracked text-sm mb-2">{item.title}</p>
              <p className="text-sm text-ink-soft">{item.body}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
